spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/postgres
    username: postgres
    password: 12345
    initialization-mode: always
    initialize: true
    continue-on-error: true
